global_args:
  trainer_backend: pl
  enable_deepspeed: false
  enable_ptv2: false
  enable_lora: false
  load_in_bit: 0
  config_merge: 
  # 模型权重 ， 对应 config.constant_map.py
  model_name: detr-resnet-50

  # one of auto 16 bf16 32
  precision: auto
  quantization_config:
    load_in_8bit: false
    load_in_4bit: false
    llm_int8_threshold: 6.0
    llm_int8_has_fp16_weight: false
    bnb_4bit_compute_dtype: float16  # one of float16  bfloat16 float32
    bnb_4bit_use_double_quant: true
    bnb_4bit_quant_type: nf4
    



global_models_mapper:
    detr-resnet-50: 
        model_type: detr
        model_name_or_path: /data/nlp/pre_models/torch/detr/detr-resnet-50
        config_name: /data/nlp/pre_models/torch/detr/detr-resnet-50/config.json
        tokenizer_name: /data/nlp/pre_models/torch/detr/detr-resnet-50
    

    detr-resnet-101: 
        model_type: detr
        model_name_or_path: /data/nlp/pre_models/torch/detr/detr-resnet-101
        config_name: /data/nlp/pre_models/torch/detr/detr-resnet-101/config.json
        tokenizer_name: /data/nlp/pre_models/torch/detr/detr-resnet-101
    
    
    yolos-base: 
        model_type: yolos
        model_name_or_path: /data/nlp/pre_models/torch/yolos/yolos-base
        config_name: /data/nlp/pre_models/torch/yolos/yolos-base/config.json
        tokenizer_name: /data/nlp/pre_models/torch/yolos/yolos-base
    

    yolos-small: 
        model_type: yolos
        model_name_or_path: /data/nlp/pre_models/torch/yolos/yolos-small
        config_name: /data/nlp/pre_models/torch/yolos/yolos-small/config.json
        tokenizer_name: /data/nlp/pre_models/torch/yolos/yolos-small
    

    yolos-tiny: 
        model_type: yolos
        model_name_or_path: /data/nlp/pre_models/torch/yolos/yolos-tiny
        config_name: /data/nlp/pre_models/torch/yolos/yolos-tiny/config.json
        tokenizer_name: /data/nlp/pre_models/torch/yolos/yolos-tiny
    

    table-transformer: 
        model_type: table-transformer
        model_name_or_path: /data/nlp/pre_models/torch/table-transformer/table-transformer-detection
        config_name: /data/nlp/pre_models/torch/table-transformer/table-transformer-detection/config.json
        tokenizer_name: /data/nlp/pre_models/torch/table-transformer/table-transformer-detection
    




